/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum ChangeType {
  AppendOnly = 0,
  Insert = 1,
  UpdateBefore = 2,
  UpdateAfter = 3,
  Delete = 4
}
export interface TableBucket {
  tableId: number
  partitionId?: number
  bucketId: number
}
export interface PartitionInfo {
  partitionId: number
  partitionName: string
}
export interface ServerNode {
  id: number
  host: string
  port: number
  serverType: string
  uid: string
}
export interface LakeSnapshotBucketOffset {
  tableId: number
  partitionId?: number
  bucketId: number
  offset: number
}
export interface DatabaseInfo {
  databaseName: string
  createdTime: number
  modifiedTime: number
}
export interface ScanRecord {
  offset: number
  timestamp: number
  changeType: string
  bucket: TableBucket
  row: any
}
/** Offset constant: start reading from the earliest available offset. */
export const EARLIEST_OFFSET: number
export declare class FlussAdmin {
  createDatabase(databaseName: string, databaseDescriptor?: DatabaseDescriptor | undefined | null, ignoreIfExists?: boolean | undefined | null): Promise<void>
  dropDatabase(databaseName: string, ignoreIfNotExists?: boolean | undefined | null, cascade?: boolean | undefined | null): Promise<void>
  listDatabases(): Promise<Array<string>>
  databaseExists(databaseName: string): Promise<boolean>
  getDatabaseInfo(databaseName: string): Promise<DatabaseInfo>
  createTable(tablePath: TablePath, tableDescriptor: TableDescriptor, ignoreIfExists?: boolean | undefined | null): Promise<void>
  dropTable(tablePath: TablePath, ignoreIfNotExists?: boolean | undefined | null): Promise<void>
  listTables(databaseName: string): Promise<Array<string>>
  tableExists(tablePath: TablePath): Promise<boolean>
  getTableInfo(tablePath: TablePath): Promise<TableInfo>
  listPartitionInfos(tablePath: TablePath): Promise<Array<PartitionInfo>>
  createPartition(tablePath: TablePath, partitionSpec: Record<string, string>, ignoreIfExists?: boolean | undefined | null): Promise<void>
  dropPartition(tablePath: TablePath, partitionSpec: Record<string, string>, ignoreIfNotExists?: boolean | undefined | null): Promise<void>
  listOffsets(tablePath: TablePath, bucketIds: Array<number>, offsetSpec: OffsetSpec): Promise<any>
  listPartitionOffsets(tablePath: TablePath, partitionName: string, bucketIds: Array<number>, offsetSpec: OffsetSpec): Promise<any>
  getServerNodes(): Promise<Array<ServerNode>>
  getLatestLakeSnapshot(tablePath: TablePath): Promise<LakeSnapshot>
}
export declare class Config {
  constructor(options?: any | undefined | null)
  /** Create a Config from a properties map (string key-value pairs). */
  static fromProperties(props: Record<string, string>): Config
  get bootstrapServers(): string
  set bootstrapServers(value: string)
  get writerAcks(): string
  set writerAcks(value: string)
  get writerRetries(): number
  set writerRetries(value: number)
  get writerBatchSize(): number
  set writerBatchSize(value: number)
  get writerEnableIdempotence(): boolean
  set writerEnableIdempotence(value: boolean)
  get securityProtocol(): string
  set securityProtocol(value: string)
  get connectTimeoutMs(): number
  set connectTimeoutMs(value: number)
}
export declare class FlussConnection {
  /** Create a new connection to a Fluss cluster (async factory). */
  static create(config: Config): Promise<FlussConnection>
  /** Get admin interface for managing databases and tables. */
  getAdmin(): FlussAdmin
  /** Get a table reference for data operations. */
  getTable(tablePath: TablePath): Promise<FlussTable>
  /** Close the connection. */
  close(): void
}
export declare class Lookuper {
  lookup(pk: any): Promise<any | null>
}
export declare class DataType {
  toStringRepr(): string
}
export declare class DataTypes {
  static boolean(): DataType
  static tinyint(): DataType
  static smallint(): DataType
  static int(): DataType
  static bigint(): DataType
  static float(): DataType
  static double(): DataType
  static string(): DataType
  static bytes(): DataType
  static binary(length: number): DataType
  static char(length: number): DataType
  static decimal(precision: number, scale: number): DataType
  static date(): DataType
  static time(): DataType
  static timeWithPrecision(precision: number): DataType
  static timestamp(): DataType
  static timestampWithPrecision(precision: number): DataType
  static timestampLtz(): DataType
  static timestampLtzWithPrecision(precision: number): DataType
}
export declare class SchemaBuilder {
  column(name: string, dataType: DataType): this
  primaryKey(columns: Array<string>): this
  build(): Schema
}
export declare class Schema {
  static builder(): SchemaBuilder
  get columnNames(): Array<string>
  get primaryKeys(): Array<string>
  getColumns(): Array<Array<string>>
}
export declare class TableDescriptorBuilder {
  schema(schema: Schema): this
  distributedBy(bucketCount?: number | undefined | null, bucketKeys?: Array<string> | undefined | null): this
  partitionedBy(keys: Array<string>): this
  comment(comment: string): this
  property(key: string, value: string): this
  customProperty(key: string, value: string): this
  logFormat(format: string): this
  kvFormat(format: string): this
  build(): TableDescriptor
}
export declare class TableDescriptor {
  static builder(): TableDescriptorBuilder
}
export declare class TablePath {
  constructor(databaseName: string, tableName: string)
  get databaseName(): string
  get tableName(): string
  toStringRepr(): string
}
export declare class TableInfo {
  get tableId(): number
  get schemaId(): number
  get tablePath(): TablePath
  get numBuckets(): number
  get createdTime(): number
  get modifiedTime(): number
  hasPrimaryKey(): boolean
  isPartitioned(): boolean
  getPrimaryKeys(): Array<string>
  getBucketKeys(): Array<string>
  getPartitionKeys(): Array<string>
  getColumnNames(): Array<string>
  get comment(): string | null
}
export declare class OffsetSpec {
  static earliest(): OffsetSpec
  static latest(): OffsetSpec
  static timestamp(ts: number): OffsetSpec
}
export declare class LakeSnapshot {
  get snapshotId(): number
  getBucketOffsets(): Array<LakeSnapshotBucketOffset>
}
export declare class DatabaseDescriptor {
  constructor(comment?: string | undefined | null, customProperties?: Record<string, string> | undefined | null)
  get comment(): string | null
}
export declare class LogScanner {
  subscribe(bucketId: number, startOffset: number): Promise<void>
  subscribeBuckets(bucketOffsets: Record<string, number>): Promise<void>
  subscribePartition(partitionId: number, bucketId: number, startOffset: number): Promise<void>
  unsubscribe(bucketId: number): Promise<void>
  unsubscribePartition(partitionId: number, bucketId: number): Promise<void>
  poll(timeoutMs: number): Promise<ScanRecords>
}
export declare class ScanRecords {
  get count(): number
  get isEmpty(): boolean
  records(): Array<ScanRecord>
}
export declare class FlussTable {
  get tablePath(): TablePath
  get hasPrimaryKey(): boolean
  getTableInfo(): TableInfo
  newAppend(): TableAppend
  newUpsert(): TableUpsert
  newLookup(): TableLookup
  newScan(): TableScan
}
export declare class TableAppend {
  createWriter(): AppendWriter
}
export declare class AppendWriter {
  append(row: any): WriteResultHandle
  flush(): Promise<void>
}
export declare class TableUpsert {
  partialUpdateByName(columns: Array<string>): TableUpsert
  partialUpdateByIndex(indices: Array<number>): TableUpsert
  createWriter(): UpsertWriter
}
export declare class TableLookup {
  createLookuper(): Lookuper
}
export declare class TableScan {
  project(indices: Array<number>): this
  projectByName(names: Array<string>): this
  createLogScanner(): LogScanner
}
export declare class UpsertWriter {
  upsert(row: any): WriteResultHandle
  delete(pk: any): WriteResultHandle
  flush(): Promise<void>
}
/**
 * Handle for a pending write operation.
 * Can be safely ignored for fire-and-forget semantics,
 * or awaited via `wait()` for per-record acknowledgment.
 */
export declare class WriteResultHandle {
  /** Wait for server acknowledgment of this specific write. */
  wait(): Promise<void>
}
