// Type definitions for @apache/fluss-wasm
// Generated by wasm-bindgen

export interface WasmConfig {
  bootstrap_servers: string;
  request_timeout_ms?: number;
  max_request_size?: number;
}

export class FlussClient {
  constructor(config: string | WasmConfig);
  getAdmin(): FlussAdmin;
  getTable(database: string, table: string): Promise<FlussTable>;
  close(): void;
}

export class FlussAdmin {
  createDatabase(databaseName: string): Promise<void>;
  listDatabases(): Promise<string[]>;
  databaseExists(databaseName: string): Promise<boolean>;
  dropDatabase(databaseName: string, ifExists?: boolean): Promise<void>;
  listTables(databaseName: string): Promise<string[]>;
  tableExists(databaseName: string, tableName: string): Promise<boolean>;
  getTableInfo(databaseName: string, tableName: string): Promise<any>;
}

export class FlussTable {
  readonly tableName: string;
  readonly databaseName: string;
  newAppend(): TableAppend;
  newUpsert(): TableUpsert;
  newScan(): TableScan;
  newLookup(): TableLookup;
}

export class TableAppend {
  append(row: any): void;
  flush(): Promise<void>;
}

export class TableUpsert {
  upsert(row: any): void;
  flush(): Promise<void>;
}

export class TableScan {
  subscribe(bucketId: number, offsetSpec: any): Promise<void>;
  poll(timeoutMs: number): Promise<any[]>;
}

export class TableLookup {
  lookup(key: any): Promise<any>;
}

export class OffsetSpec {
  static earliest(): any;
  static latest(): any;
  static timestamp(ts: number): any;
}

export function version(): string;
